ДП_WebУчетИностранныхСтудентов/ViewModels/QuestionnaireVM/EditQuestionnaireViewModel.cs
using MonitoringTheProgressOfForeignStudents.Domain.Model;
using System.ComponentModel.DataAnnotations;

namespace MonitoringTheProgressOfForeignStudents.ViewModels.QuestionnaireVM
{
    public class EditQuestionnaireViewModel
    {
        public Guid? PersonalDetailsId { get; set; }
        [MaxLength(40)]
        public string Name { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? Surname { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? Patronymic { get; set; } = string.Empty;
        [Required(ErrorMessage = "Необходимо указать дату рождения")]
        public DateTime Birthday { get; set; }
        [Required(ErrorMessage = "Необходимо указать место рождения")]
        [MaxLength(150)]
        public string PlaceofBirth { get; set; } = string.Empty;
        [Required(ErrorMessage = "Необходимо указать постоянный адрес проживания")]
        [MaxLength(150)]
        public string PermamentHomeAddress { get; set; } = string.Empty;
        [MaxLength(20)]
        public string? PhoneNumber { get; set; } = string.Empty;
        [MaxLength(20)]
        public string? PhoneNumberInBelarus { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? Email { get; set; } = string.Empty;

        [Required(ErrorMessage = "Необходимо указать пол")]
        public Guid? GenderId { get; set; }
        [Required(ErrorMessage = "Необходимо указать страну")]
        public Guid? CountryId { get; set; }
        [Required(ErrorMessage = "Необходимо указать национальность")]
        public Guid? NationalityId { get; set; }
        [Required(ErrorMessage = "Необходимо указать семейное положение")]
        public Guid? MaritalStatusId { get; set; }
        //
        [MaxLength(150)]
        public string? FathersName { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? FathersProfession { get; set; } = string.Empty;
        [MaxLength(20)]
        public string? FathersPhone { get; set; } = string.Empty;
        [MaxLength(150)]
        public string? MothersName { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? MothersProfession { get; set; } = string.Empty;
        [MaxLength(20)]
        public string? MothersPhone { get; set; } = string.Empty;
        [MaxLength(50)]
        public string? NameOfSchool { get; set; } = string.Empty;
        [MaxLength(150)]
        public string? AddressOfSchool { get; set; } = string.Empty;
        public DateTime? DateOfEntrance { get; set; }
        public DateTime? DateOfCompletion { get; set; }
        [MaxLength(200)]
        public string? KnowledgeOfLanguages { get; set; } = string.Empty;
        [MaxLength(200)]
        public string? RelativeToBeInformedInEmergency { get; set; } = string.Empty;
        [MaxLength(200)]
        public string? HowDidYouFindOutAboutBNTU { get; set; } = string.Empty;

        //
        [Required(ErrorMessage = "Необходимо указать специальность")]
        public Guid? SpecialtyId { get; set; }
        [Required(ErrorMessage = "Необходимо указать язык образования")]
        public Guid? EducationLanguageId { get; set; }
        [Required(ErrorMessage = "Необходимо указать тип образования")]
        public Guid? EducationTypeId { get; set; }

        public List<Order>? Orders { get; set; }
        public List<Order>? Reprimands { get; set; }

        //
        public List<Home>? Homes { get; set; }
    }
}

ДП_WebУчетИностранныхСтудентов/Controllers/QuestionnaireController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MonitoringTheProgressOfForeignStudents.Application.Interfaces.Repositories;
using MonitoringTheProgressOfForeignStudents.Application.Interfaces.Services;
using MonitoringTheProgressOfForeignStudents.Domain.Model;
using MonitoringTheProgressOfForeignStudents.ViewModels.QuestionnaireVM;

namespace MonitoringTheProgressOfForeignStudents.Controllers
{
    [Route("[controller]")]
    [Authorize(Policy = "RequireWorkerRoles")]
    public class QuestionnaireController : Controller
    {
        private readonly EditQuestionnaireVMConverter converter;
        private readonly IOfficeService wordService;
        private readonly IQuestionnaireRepository questionnaireRepository;
        private readonly IGenderRepository genderRepository;
        private readonly ICountryRepository countryRepository;
        private readonly INationalityRepository nationalityRepository;
        private readonly IMaritalStatusRepository maritalStatusRepository;
        private readonly ISpecialtyRepository specialtyRepository;
        private readonly IEducationLanguageRepository educationLanguageRepository;
        private readonly IEducationTypeRepository educationTypeRepository;
        private readonly IPersonalDetailsRepository personalDetailsRepository;
        private readonly IOrderRepository orderRepository;
        private readonly IHomeRepository homeRepository;

        public QuestionnaireController(EditQuestionnaireVMConverter converter,
            IOfficeService wordService,
            IQuestionnaireRepository questionnaireRepository,
            IGenderRepository genderRepository,
            ICountryRepository countryRepository,
            INationalityRepository nationalityRepository,
            IMaritalStatusRepository maritalStatusRepository,
            ISpecialtyRepository specialtyRepository,
            IEducationLanguageRepository educationLanguageRepository,
            IEducationTypeRepository educationTypeRepository,
            IPersonalDetailsRepository personalDetailsRepository,
            IOrderRepository orderRepository,
            IHomeRepository homeRepository)
        {
            this.converter = converter;
            this.wordService = wordService;
            this.questionnaireRepository = questionnaireRepository;
            this.genderRepository = genderRepository;
            this.countryRepository = countryRepository;
            this.nationalityRepository = nationalityRepository;
            this.maritalStatusRepository = maritalStatusRepository;
            this.specialtyRepository = specialtyRepository;
            this.educationLanguageRepository = educationLanguageRepository;
            this.educationTypeRepository = educationTypeRepository;
            this.personalDetailsRepository = personalDetailsRepository;
            this.orderRepository = orderRepository;
            this.homeRepository = homeRepository;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            InitViewBag();
            return View(new GetQuestionnaireListViewModel
            {
                QuestionnaireViewModels = questionnaireRepository.GetAllFull().AsEnumerable()
                .Select(x => new GetQuestionnaireViewModel
                {
                    Id = x.Id,
                    PersonalId = x.PersonalDetailsId,
                    Created = x.Created,
                    Name = x.PersonalDetails.Name,
                    Surname = x.PersonalDetails.Surname ?? string.Empty,
                    Patronymic = x.PersonalDetails.Patronymic ?? string.Empty,
                    Email = x.PersonalDetails.Email ?? string.Empty,
                    Gender = x.PersonalDetails.Gender?.Name ?? string.Empty,
                    Country = x.PersonalDetails.Country?.Name ?? string.Empty,
                    MaritalStatus = x.PersonalDetails.MaritalStatus?.Name ?? string.Empty,
                    Nationality = x.PersonalDetails.Nationality?.Name ?? string.Empty,
                    Faculty = x.Specialty?.Faculty?.Name ?? string.Empty,
                    Specialty = x.Specialty?.Name ?? string.Empty,
                    SpecialtyCode = x.Specialty?.Code ?? string.Empty
                })
                .GroupBy(x => x.PersonalId)
                .Select(x => x.OrderByDescending(f => f.Created).First()).ToList()
                .OrderByDescending(x => x.Created).ToList()
            });
        }

        [HttpPost]
        [Route("")]
        public IActionResult Index(GetQuestionnaireListViewModel viewModel)
        {
            InitViewBag();
            viewModel.QuestionnaireViewModels = SearchQuestionnaires(viewModel).ToList();
            return View(viewModel);
        }

        [HttpPost]
        [Route("get-file-list")]
        public FileResult GetFileList(GetQuestionnaireListViewModel questionnaireViewModel)
        {
            var viewmodels = SearchQuestionnaires(questionnaireViewModel).Select(x => new ExcelQuestionnaireViewModel
            {
                Surname = x.Surname,
                Name = x.Name,
                Patronymic = x.Patronymic,
                Email = x.Email,
                Country = x.Country,
                Nationality = x.Nationality,
                Gender = x.Gender,
                MaritalStatus = x.MaritalStatus,
                Specialty = x.Specialty,
                SpecialtyCode = x.SpecialtyCode,
                Faculty = x.Faculty,
            });
            var names = new List<string>
            {
                "Фамилия", "Имя", "Отчество", "Почта", "Страна", "Национальность", "Пол", "Семейное положение", "Спецальность", "Код специальности", "Факультет"
            };
            return File(wordService.ExportExcel(viewmodels, names), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{DateTime.Now}.xlsx");
        }

        [HttpGet]
        [Route("history/{personalId}")]
        public IActionResult History(Guid personalId)
        {
            return View(questionnaireRepository.GetAllFull()
                .Where(x => x.PersonalDetailsId == personalId)
                .OrderByDescending(f => f.Created).ToList()
                .Select(x => new GetQuestionnaireViewModel
                {
                    Id = x.Id,
                    PersonalId = x.PersonalDetailsId,
                    Created = x.Created,
                    Name = x.PersonalDetails.Name,
                    Surname = x.PersonalDetails.Surname ?? string.Empty,
                    Patronymic = x.PersonalDetails.Patronymic ?? string.Empty,
                    Email = x.PersonalDetails.Email ?? string.Empty,
                    Gender = x.PersonalDetails.Gender?.Name ?? string.Empty,
                    Country = x.PersonalDetails.Country?.Name ?? string.Empty,
                    MaritalStatus = x.PersonalDetails.MaritalStatus?.Name ?? string.Empty,
                    Nationality = x.PersonalDetails.Nationality?.Name ?? string.Empty,
                    Faculty = x.Specialty?.Faculty?.Name ?? string.Empty,
                    Specialty = x.Specialty?.Name ?? string.Empty,
                    SpecialtyCode = x.Specialty?.Code ?? string.Empty
                }));
        }

        [HttpPost]
        [Route("get-file")]
        public async Task<FileResult> GetFile(EditQuestionnaireViewModel questionnaireViewModel)
        {
            string fileName = @"АНКЕТА.docx";
            var questFile = new QuestionnaireFileViewModel(questionnaireViewModel);
            questFile.Gender = (await genderRepository.GetById(questionnaireViewModel.GenderId ?? Guid.Empty))?.Name ?? "Пол не определен";
            questFile.Country = (await countryRepository.GetById(questionnaireViewModel.CountryId ?? Guid.Empty))?.Name ?? "Страна не определена";
            questFile.MaritalStatus = (await maritalStatusRepository.GetById(questionnaireViewModel.MaritalStatusId ?? Guid.Empty))?.Name ?? "Семейное положение не определено";
            questFile.Nationality = (await nationalityRepository.GetById(questionnaireViewModel.NationalityId ?? Guid.Empty))?.Name ?? "Национальность не определена";
            questFile.Specialty = (await specialtyRepository.GetById(questionnaireViewModel.SpecialtyId ?? Guid.Empty))?.Name ?? "Специальность не определена";
            var dict = questFile.ToFileDict();
            return File(wordService.ReplaceTemplate(fileName, dict), "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                $"{questFile.Name} {questFile.Surname} {questFile.Patronymic} {DateTime.Now}.docx");
        }
        [HttpPost]
        [Route("get-declaration")]
        public async Task<FileResult> GetDeclaration(EditQuestionnaireViewModel questionnaireViewModel)
        {
            string fileName = @"модель.xlsx";
            var questFile = new QuestionnaireFileViewModel(questionnaireViewModel);
            questFile.Gender = (await genderRepository.GetById(questionnaireViewModel.GenderId ?? Guid.Empty))?.Name ?? "Пол не определен";
            questFile.Country = (await countryRepository.GetById(questionnaireViewModel.CountryId ?? Guid.Empty))?.Name ?? "Страна не определена";
            questFile.MaritalStatus = (await maritalStatusRepository.GetById(questionnaireViewModel.MaritalStatusId ?? Guid.Empty))?.Name ?? "Семейное положение не определено";
            questFile.Nationality = (await nationalityRepository.GetById(questionnaireViewModel.NationalityId ?? Guid.Empty))?.Name ?? "Национальность не определена";
            questFile.Specialty = (await specialtyRepository.GetById(questionnaireViewModel.SpecialtyId ?? Guid.Empty))?.Name ?? "Специальность не определена";
            var dict = questFile.ToFileDict();

ДП_WebУчетИностранныхСтудентов/Views/Questionnaire/History.cshtml
@model IEnumerable<GetQuestionnaireViewModel>

@{
    ViewBag.Title = "История анкет";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h1>История анкеты:</h1>
    </div>
    @foreach (var item in Model)
    {
        <div class="border border-3 border-success rounded-pill m-1 bg-list-block">
            <div class="border border-3 border-success rounded-pill m-2 bg-white">
                <div class="row mx-auto">
                    <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-start align-items-center fs-5">
                        Дата изменения: @item.Created
                    </div>
                    <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-end align-items-center">
                        <div class="m-1">
                            <a asp-controller="Questionnaire" asp-action="EditQuestionnaire" asp-route-Id="@item.Id"><input type="button" class="btn btn-success" value="Редактировать"></a>
                        </div>
                        <div class="m-1">
                            <form asp-controller="Questionnaire" asp-action="DeleteQuestionnaire" method="post" asp-route-id="@item.Id">
                                <input class="btn btn-success" type="submit" value="Удалить" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ДП_WebУчетИностранныхСтудентов/Views/Questionnaire/Index.cshtml
@model GetQuestionnaireListViewModel

@{
    ViewBag.Title = "Список анкет";
    Layout = "_Layout";
}

<div class="container">
    <div class="border border-3 border-success rounded m-1 bg-list-block">
        <div class="border border-3 border-success rounded m-2 bg-white">
            <form class="m-2" method="post">
                <div class="fs-5 align-content-center align-items-center">Поиск</div>
                <div class="validation" asp-validation-summary="ModelOnly"></div>
                <div class="mx-auto">
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <input class="form-control m-1" asp-for="SearchQuestionnaire.SearchString" placeholder="Универсальный поиск" />
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.GenderId" asp-items="ViewBag.Genders">
                            <option value="@Guid.Empty">Выберите пол</option>
                            <option value="@null">Не определено</option>
                        </select>
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.MaritalStatusId" asp-items="ViewBag.MaritalStatuses">
                            <option value="@Guid.Empty">Выберите семейное положение</option>
                            <option value="@null">Не определено</option>
                        </select>
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.CountryId" asp-items="ViewBag.Countries">
                            <option value="@Guid.Empty">Выберите страну</option>
                            <option value="@null">Не определено</option>
                        </select>
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.NationalityId" asp-items="ViewBag.Nationalities">
                            <option value="@Guid.Empty">Выберите национальность</option>
                            <option value="@null">Не определено</option>
                        </select>
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.SpecialtyId" asp-items="ViewBag.Specialties">
                            <option value="@Guid.Empty">Выберите специальность</option>
                            <option value="@null">Не определено</option>
                        </select>
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.EducationTypeId" asp-items="ViewBag.EduType">
                            <option value="@Guid.Empty">Выберите тип обучения</option>
                            <option value="@null">Не определено</option>
                        </select>
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <select class="form-select m-1" asp-for="SearchQuestionnaire.EducationLanguageId" asp-items="ViewBag.EduLang">
                            <option value="@Guid.Empty">Выберите язык обучения</option>
                            <option value="@null">Не определено</option>
                        </select>
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <button asp-controller="Questionnaire" asp-action="Index" type="submit" class="btn btn-success m-1">Найти</button>
                        <button asp-controller="Questionnaire" asp-action="GetFileList" type="submit" class="btn btn-outline-success m-1">В файл</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="d-flex justify-content-center justify-content-md-start">
        <h1>Список анкет:</h1>
    </div>
    <div class="d-flex justify-content-center justify-content-md-start">
        <a asp-controller="Questionnaire" asp-action="AddQuestionnaire"><input type="submit" class="btn btn-success" value="Добавить" /></a>
    </div>
    <div class="row mx-auto">
        @foreach (var item in Model.QuestionnaireViewModels)
        {
            <div class="col-12 col-sm-6 col-md-4 d-flex justify-content-center justify-content-md-start align-items-center">
                <div class="border border-3 border-success rounded m-1 bg-list-block">
                    <div class="border border-3 border-success rounded m-2 bg-white">
                        <div class="m-1">
                            <fieldset disabled>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">ФИО</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Surname">
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Name">
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Patronymic">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Email</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Email">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Семейное положение</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.MaritalStatus">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Пол</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Gender">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Национальность</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Nationality">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Страна</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Country">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Факультет</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Faculty">
                                </div>
                                <hr>
                                <div class="input-group">
                                    <span class="input-group-text text-muted">Специальность</span>
                                    <input type="text" class="input-group-text form-control" asp-for="@item.Specialty">
                                    <input type="text" class="input-group-text form-control" asp-for="@item.SpecialtyCode">
                                </div>
                            </fieldset>
                            <div class="row my-1 d-flex justify-content-center align-items-center">
                                <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-start align-items-center">
                                    <a asp-controller="Questionnaire" asp-action="History" asp-route-Id="@item.PersonalId"><input type="button" class="btn btn-outline-success" value="История"></a>
                                </div>
                                <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-end align-items-center">
                                    <a asp-controller="StudentCard" asp-action="AddStudentCard" asp-route-personalDetailsId="@item.PersonalId"><input type="button" class="btn btn-outline-success" value="Карточка"></a>
                                </div>
                            </div>
                            <div class="row my-1 d-flex justify-content-center align-items-center">
                                <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-start align-items-center">
                                    <a asp-controller="Questionnaire" asp-action="EditQuestionnaire" asp-route-Id="@item.Id"><input type="button" class="btn btn-success" value="Редактировать"></a>
                                </div>
                                <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-end align-items-center">
                                    <form asp-controller="Questionnaire" asp-action="DeleteQuestionnaire" method="post" asp-route-id="@item.Id">
                                        <input type="submit" class="btn btn-success" value="Удалить" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>