ДП_WebУчетИностранныхСтудентов/ViewModels/EducationLanguageVM/EditEducationLanguageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MonitoringTheProgressOfForeignStudents.ViewModels.EducationLanguageVM
{
    public class EditEducationLanguageViewModel
    {
        [Required(ErrorMessage = "Необходимо указать язык")]
        [MaxLength(20)]
        public string Language { get; set; }
    }
}

ДП_WebУчетИностранныхСтудентов/Controllers/EducationLanguageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MonitoringTheProgressOfForeignStudents.Application.Interfaces.Repositories;
using MonitoringTheProgressOfForeignStudents.Domain.Model;
using MonitoringTheProgressOfForeignStudents.ViewModels.EducationLanguageVM;

namespace MonitoringTheProgressOfForeignStudents.Controllers
{
    [Route("[controller]")]
    [Authorize(Policy = "RequireWorkerRoles")]
    public class EducationLanguageController : Controller
    {
        private readonly EditEducationLanguageVMConverter converter;
        private readonly IEducationLanguageRepository repository;
        private readonly IQuestionnaireRepository questionnaireRepository;

        public EducationLanguageController(EditEducationLanguageVMConverter converter,
                                            IEducationLanguageRepository repository,
                                            IQuestionnaireRepository questionnaireRepository)
        {
            this.converter = converter;
            this.repository = repository;
            this.questionnaireRepository = questionnaireRepository;
        }

        [Route("")]
        [HttpGet]
        public IActionResult GetAll()
        {
            var latestQuestionnaires = questionnaireRepository.GetAllFull()
                .GroupBy(x => x.PersonalDetails)
                .Select(x => x.OrderByDescending(f => f.Created).First()).ToList();

            return View(new GetEducationLanguageListViewModel
            {
                EducationLanguageViewModels = repository.GetAllFull()
                .OrderByDescending(x => x.Created).AsEnumerable()
                .Select(x => new GetEducationLanguageViewModel
                {
                    Id = x.Id,
                    Language = x.Language,
                    QuestionnairesCount = latestQuestionnaires.Count(q => q.EducationLanguageId == x.Id),
                })
            });
        }

        [Route("")]
        [HttpPost]
        public IActionResult GetAll(GetEducationLanguageListViewModel viewModel)
        {
            var latestQuestionnaires = questionnaireRepository.GetAllFull()
                .GroupBy(x => x.PersonalDetails)
                .Select(x => x.OrderByDescending(f => f.Created).First()).ToList();

            var eduLangs = repository.GetAllFull().OrderByDescending(x => x.Created).AsEnumerable();

            if (!string.IsNullOrEmpty(viewModel.SearchEducationLanguage.SearchString))
            {
                eduLangs = eduLangs.Where(x => x.Language.ToLower().Contains(viewModel.SearchEducationLanguage.SearchString.ToLower()));
            }

            viewModel.EducationLanguageViewModels = eduLangs
                .Select(x => new GetEducationLanguageViewModel
                {
                    Id = x.Id,
                    Language = x.Language,
                    QuestionnairesCount = latestQuestionnaires.Count(q => q.EducationLanguageId == x.Id),
                });

            return View(viewModel);
        }

        [Route("add")]
        [HttpGet]
        public IActionResult AddEducationLanguage()
        {
            return View();
        }

        [Route("add")]
        [HttpPost]
        public async Task<IActionResult> AddEducationLanguage(EditEducationLanguageViewModel educationLanguageViewModel)
        {
            if (ModelState.IsValid)
            {
                if (!repository.GetAll().Any(x => x.Language.ToLower() == educationLanguageViewModel.Language.ToLower()))
                {
                    var language = converter.ConvertTo(educationLanguageViewModel);
                    await repository.CreateAsync(language);
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("", "Данный язык уже есть в базе");
            }

            return View(educationLanguageViewModel);
        }

        [Route("edit/{id}")]
        [HttpGet]
        public async Task<IActionResult> EditEducationLanguage(Guid id)
        {
            var language = await repository.GetById(id);

            if (language != null)
            {
                return View(converter.ConvertFrom(language));
            }

            return NotFound();
        }

        [Route("edit/{id}")]
        [HttpPost]
        public async Task<IActionResult> EditEducationLanguage(Guid id, EditEducationLanguageViewModel educationLanguageViewModel)
        {
            if (ModelState.IsValid)
            {
                if (!repository.GetAll().Any(x => x.Language.ToLower() == educationLanguageViewModel.Language.ToLower()
                                                                && id != x.Id))
                {
                    var language = await repository.GetById(id);

                    if (language != null)
                    {
                        language = converter.Update(educationLanguageViewModel, language);
                        await repository.UpdateAsync(language);

                        return RedirectToAction("Index");
                    }

                    return NotFound();
                }

                ModelState.AddModelError("", "Данный язык уже есть в базе");
            }

            return View(educationLanguageViewModel);
        }

        [Route("deleteedulang")]
        [HttpPost]
        public async Task<IActionResult> DeleteEducationLanguage(Guid id)
        {
            var language = await repository.GetById(id);

            if (language != null)
            {
                await repository.DeleteAsync(language);
            }
            return RedirectToAction("Index");
        }
    }
}

ДП_WebУчетИностранныхСтудентов/Views/EducationLanguage/AddEducationLanguage.cshtml
@model EditEducationLanguageViewModel

@{
    ViewBag.Title = "Добавить язык";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h2>Добавление языка</h2>
    </div>
    <div class="row mx-auto d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-6 ">
            <div class="border border-3 border-success rounded m-1 bg-list-block">
                <div class="border border-3 border-success rounded m-2 bg-white">
                    <form class="m-2" asp-action="AddEducationLanguage" asp-controller="EducationLanguage" method="post">
                        <div class="validation text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="mb-3">
                            <label class="form-label">Язык</label>
                            <input type="text" class="form-control" placeholder="Введите язык" asp-for="Language">
                            <div class="form-text">Язык должен быть уникальным!</div>
                            <span class="form-text text-danger" asp-validation-for="Language"></span>
                        </div>
                        <button type="submit" class="btn btn-success">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ДП_WebУчетИностранныхСтудентов/Views/EducationLanguage/EditEducationLanguage.cshtml
@model EditEducationLanguageViewModel

@{
    ViewBag.Title = "Редактировать язык";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h2>Редактирование языка</h2>
    </div>
    <div class="row mx-auto d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-6 ">
            <div class="border border-3 border-success rounded m-1 bg-list-block">
                <div class="border border-3 border-success rounded m-2 bg-white">
                    <form class="m-2" asp-action="EditEducationLanguage" asp-controller="EducationLanguage" method="post">
                        <div class="validation text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="mb-3">
                            <label class="form-label">Язык</label>
                            <input type="text" class="form-control" placeholder="Введите язык" asp-for="Language">
                            <div class="form-text">Язык должен быть уникальным!</div>
                            <span class="form-text text-danger" asp-validation-for="Language"></span>
                        </div>
                        <button type="submit" class="btn btn-success">Обновить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ДП_WebУчетИностранныхСтудентов/Views/EducationLanguage/GetAll.cshtml
@model GetEducationLanguageListViewModel

@{
    ViewBag.Title = "Список языков";
    Layout = "_Layout";
}

<div class="container">
    <div class="border border-3 border-success rounded m-1 bg-list-block">
        <div class="border border-3 border-success rounded m-2 bg-white">
            <form class="m-2" method="post">
                <div class="fs-5 align-content-center align-items-center">Поиск</div>
                <div class="validation" asp-validation-summary="ModelOnly"></div>
                <div class="mx-auto">
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <input class="form-control m-1" asp-for="SearchEducationLanguage.SearchString" placeholder="Поиск" />
                    </div>
                    <div class="col-12 d-flex justify-content-center justify-content-md-start align-items-center">
                        <button asp-controller="EducationLanguage" asp-action="GetAll" type="submit" class="btn btn-success m-1">Найти</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="d-flex justify-content-center justify-content-md-start">
        <h1>Список языков:</h1>
    </div>
    <div class="d-flex justify-content-center justify-content-md-start">
        <a asp-controller="EducationLanguage" asp-action="AddEducationLanguage"><input type="submit" class="btn btn-success" value="Добавить" /></a>
    </div>
    @foreach (var lang in Model.EducationLanguageViewModels)
    {
        <div class="border border-3 border-success rounded-pill m-1 bg-list-block">
            <div class="border border-3 border-success rounded-pill m-2 bg-white">
                <div class="row mx-auto">
                    <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-start align-items-center fs-5">
                        Название: @lang.Language
                    </div>
                    <div class="col-12 col-md-3 d-flex justify-content-center justify-content-md-start align-items-center fs-5">
                        Студентов: @lang.QuestionnairesCount
                    </div>
                    <div class="col-12 col-md-3 d-flex justify-content-center justify-content-md-end align-items-center">
                        <div class="m-1">
                            <a asp-controller="EducationLanguage" asp-action="EditEducationLanguage" asp-route-Id="@lang.Id"><input type="button" class="btn btn-success" value="Редактировать"></a>
                        </div>
                        <div class="m-1">
                            <form asp-controller="EducationLanguage" asp-action="DeleteEducationLanguage" method="post" asp-route-id="@lang.Id">
                                <input class="btn btn-success" type="submit" value="Удалить" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>