ДП_WebУчетИностранныхСтудентов/ViewModels/StudentCardVM/EditStudentCardViewModel.cs
using MonitoringTheProgressOfForeignStudents.Domain.Model;

namespace MonitoringTheProgressOfForeignStudents.ViewModels.StudentCardVM
{
    public class EditStudentCardViewModel
    {
        public Guid PersonalDetailsId { get; set; }
        public string? Name { get; set; } = string.Empty;
        public string? Surname { get; set; } = string.Empty;
        public string? Patronymic { get; set; } = string.Empty;
        public DateTime? Birthday { get; set; }
        public string? Gender { get; set; }
        public string? Country { get; set; }
        public string? Faculty { get; set; }
        public string? PlaceofBirth { get; set; } = string.Empty;

        public List<Home>? Homes { get; set; }

        public List<PassportInfo>? Passports { get; set; }
        public List<Register>? Registers { get; set; }
    }
}

ДП_WebУчетИностранныхСтудентов/Controllers/StudentCardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MonitoringTheProgressOfForeignStudents.Application.Interfaces.Repositories;
using MonitoringTheProgressOfForeignStudents.Application.Interfaces.Services;
using MonitoringTheProgressOfForeignStudents.Domain.Model;
using MonitoringTheProgressOfForeignStudents.ViewModels.QuestionnaireVM;
using MonitoringTheProgressOfForeignStudents.ViewModels.StudentCardVM;

namespace MonitoringTheProgressOfForeignStudents.Controllers
{
    [Route("[controller]")]
    [Authorize(Policy = "RequireWorkerRoles")]
    public class StudentCardController : Controller
    {
        private readonly EditStudentCardVMConverter converter;
        private readonly IOfficeService wordService;
        private readonly IStudentCardRepository studentCardRepository;
        private readonly IPersonalDetailsRepository personalDetailsRepository;
        private readonly IRegisterRepository registerRepository;
        private readonly IPassportInfoRepository passportInfoRepository;
        private readonly INationalityRepository nationalityRepository;
        private readonly IMaritalStatusRepository maritalStatusRepository;
        private readonly IGenderRepository genderRepository;
        private readonly ICountryRepository countryRepository;

        public StudentCardController(EditStudentCardVMConverter converter,
            IOfficeService wordService,
            IStudentCardRepository studentCardRepository,
            IPersonalDetailsRepository personalDetailsRepository,
            IRegisterRepository registerRepository,
            IPassportInfoRepository passportInfoRepository,
            INationalityRepository nationalityRepository,
            IMaritalStatusRepository maritalStatusRepository,
            IGenderRepository genderRepository,
            ICountryRepository countryRepository)
        {
            this.converter = converter;
            this.wordService = wordService;
            this.studentCardRepository = studentCardRepository;
            this.personalDetailsRepository = personalDetailsRepository;
            this.registerRepository = registerRepository;
            this.passportInfoRepository = passportInfoRepository;
            this.nationalityRepository = nationalityRepository;
            this.maritalStatusRepository = maritalStatusRepository;
            this.genderRepository = genderRepository;
            this.countryRepository = countryRepository;
        }

        [HttpGet]
        [Route("history/{personalId}")]
        public IActionResult History(Guid personalId)
        {
            return View(studentCardRepository.GetAllFull()
                .Where(x => x.PersonalDetailsId == personalId)
                .OrderByDescending(f => f.Created).ToList()
                .Select(x => new GetStudentCardViewModel
                {
                    Id = x.Id,
                    PersonalId = x.PersonalDetailsId,
                    Created = x.Created,
                    Name = x.PersonalDetails.Name,
                    Surname = x.PersonalDetails.Surname ?? "",
                    Patronymic = x.PersonalDetails.Patronymic ?? "",
                    Email = x.PersonalDetails.Email ?? "",
                    Gender = x.PersonalDetails.Gender?.Name ?? string.Empty,
                    Country = x.PersonalDetails.Country?.Name ?? string.Empty,
                    MaritalStatus = x.PersonalDetails.MaritalStatus?.Name ?? string.Empty,
                    Nationality = x.PersonalDetails.Nationality?.Name ?? string.Empty,
                }).OrderByDescending(x => x.Created));
        }

        [HttpPost]
        [Route("get-file-list")]
        public FileResult GetFileList(GetStudentCardListViewModel viewModel)
        {
            var viewmodels = SearchStudentCards(viewModel).Select(x => new ExcelStudentCardViewModel
            {
                Surname = x.Surname,
                Name = x.Name,
                Patronymic = x.Patronymic,
                Email = x.Email,
                Country = x.Country,
                Nationality = x.Nationality,
                Gender = x.Gender,
                MaritalStatus = x.MaritalStatus,
                PassportValid = x.PassportValid,
                RegisterValid = x.RegisterValid,
            });
            var names = new List<string>
            {
                "Фамилия", "Имя", "Отчество", "Почта", "Страна", "Национальность", "Пол", "Семейное положение", "Пасспорт действителен?", "Регистрация действительна?"
            };
            return File(wordService.ExportExcel(viewmodels, names), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{DateTime.Now}.xlsx");
        }

        [HttpPost]
        [Route("get-file")]
        public FileResult GetFile(EditStudentCardViewModel studentCardViewModel)
        {
            string fileName = @"blank.docx";
            var cardFile = new StudentCardFileViewModel(studentCardViewModel);
            var dict = cardFile.ToFileDict();
            return File(wordService.ReplaceTemplate(fileName, dict), "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                $"{cardFile.Name} {cardFile.Surname} {cardFile.Patronymic} {DateTime.Now}.docx");
        }

        [HttpGet]
        [Route("")]
        public IActionResult GetAll()
        {
            ViewBag.Nationalities = new SelectList(nationalityRepository.GetAll(), nameof(Nationality.Id), nameof(Nationality.Name));
            ViewBag.MaritalStatuses = new SelectList(maritalStatusRepository.GetAll(), nameof(MaritalStatus.Id), nameof(MaritalStatus.Name));
            ViewBag.Genders = new SelectList(genderRepository.GetAll(), nameof(Gender.Id), nameof(Gender.Name));
            ViewBag.Countries = new SelectList(countryRepository.GetAll(), nameof(Country.Id), nameof(Country.Name));
            return View(new GetStudentCardListViewModel
            {
                StudentCardViewModels = studentCardRepository.GetAllFull().AsEnumerable()
                .Select(x => new GetStudentCardViewModel
                {
                    Id = x.Id,
                    PersonalId = x.PersonalDetailsId,
                    Created = x.Created,
                    Name = x.PersonalDetails.Name,
                    Surname = x.PersonalDetails.Surname ?? "",
                    Patronymic = x.PersonalDetails.Patronymic ?? "",
                    Email = x.PersonalDetails.Email ?? "",
                    Gender = x.PersonalDetails.Gender?.Name ?? string.Empty,
                    Country = x.PersonalDetails.Country?.Name ?? string.Empty,
                    MaritalStatus = x.PersonalDetails.MaritalStatus?.Name ?? string.Empty,
                    Nationality = x.PersonalDetails.Nationality?.Name ?? string.Empty,
                })
                .GroupBy(x => x.PersonalId)
                .Select(x => x.OrderByDescending(f => f.Created).First())
            });
        }

        [HttpPost]
        [Route("")]
        public IActionResult GetAll(GetStudentCardListViewModel viewModel)
        {
            ViewBag.Nationalities = new SelectList(nationalityRepository.GetAll(), nameof(Nationality.Id), nameof(Nationality.Name));
            ViewBag.MaritalStatuses = new SelectList(maritalStatusRepository.GetAll(), nameof(MaritalStatus.Id), nameof(MaritalStatus.Name));
            ViewBag.Genders = new SelectList(genderRepository.GetAll(), nameof(Gender.Id), nameof(Gender.Name));
            ViewBag.Countries = new SelectList(countryRepository.GetAll(), nameof(Country.Id), nameof(Country.Name));

            viewModel.StudentCardViewModels = SearchStudentCards(viewModel);

            return View(viewModel);
        }

        [Route("add/{PersonalDetailsId}")]
        [HttpGet]
        public async Task<IActionResult> AddStudentCard(Guid personalDetailsId)
        {
            var sCard = studentCardRepository.GetAll()
                .Where(x => x.PersonalDetailsId == personalDetailsId)
                .OrderByDescending(x => x.Created)
                .FirstOrDefault();

            if (sCard == null)
            {
                var personalDetails = await personalDetailsRepository.GetAllFull()
                    .FirstOrDefaultAsync(x => x.Id == personalDetailsId);

                if (personalDetails != null)
                {
                    var studentCardViewModel = converter.ConvertFrom(new StudentCard
                    {
                        PersonalDetails = personalDetails
                    });

                    return View(studentCardViewModel);
                }
            }
            else
            {
                return RedirectToAction("EditStudentCard", new { id = sCard.Id });
            }

            return NotFound();
        }

        [Route("add/{PersonalDetailsId}")]
        [HttpPost]
        public async Task<IActionResult> AddStudentCard(Guid personalDetailsId, EditStudentCardViewModel studentCardViewModel)
        {
            if (ModelState.IsValid)
            {
                var personalDetails = await personalDetailsRepository.GetAllFull()
                    .FirstOrDefaultAsync(x => x.Id == personalDetailsId);

                var pas = studentCardViewModel.Passports;
                var reg = studentCardViewModel.Registers;

                studentCardViewModel = converter.ConvertFrom(new Domain.Model.StudentCard
                {
                    PersonalDetails = personalDetails,
                });

                studentCardViewModel.Passports = pas;
                studentCardViewModel.Registers = reg;

                var studentCard = converter.ConvertTo(studentCardViewModel);

                await studentCardRepository.CreateAsync(studentCard);

                return RedirectToAction("Index");
            }

            return View(studentCardViewModel);
        }

ДП_WebУчетИностранныхСтудентов/Views/StudentCard/AddStudentCard.cshtml
@model EditStudentCardViewModel

@{
    ViewBag.Title = "Создание карточки";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h2>Добавление карточки студента</h2>
    </div>
    <div class="row mx-auto d-flex justify-content-center align-items-center">
        <div class="col-12">
            <div class="border border-3 border-success rounded m-1 bg-list-block">
                <div class="border border-3 border-success rounded m-2 bg-white">
                    <form class="m-2" method="post" asp-controller="StudentCard" asp-action="AddStudentCard">
                        <div class="validation text-danger" asp-validation-summary="ModelOnly"></div>
                        <input type="hidden" asp-for="PersonalDetailsId" value="@Model.PersonalDetailsId" />
                        <div class="row mx-auto">
                            <div class="col-12 d-flex justify-content-center align-items-center">
                                <h3>Карточка студента @Model.Surname @Model.Name @Model.Patronymic</h3>
                            </div>
                            <div class="col-12 d-flex justify-content-center align-items-center mb-3">
                                Личные данные
                            </div>
                            <div class="col-12">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Фамилия, имя, отвество</span>
                                        <input type="text" class="form-control" asp-for="Surname">
                                        <input type="text" class="form-control" asp-for="Name">
                                        <input type="text" class="form-control" asp-for="Patronymic">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Факультет</span>
                                        <input type="text" class="form-control" asp-for="Faculty">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Гражданство</span>
                                        <input type="text" class="form-control" asp-for="Country">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Пол</span>
                                        <input type="text" class="form-control" asp-for="Gender">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Дата рождения</span>
                                        <input type="date" class="form-control" asp-for="Birthday">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Место рождения</span>
                                        <input type="text" class="form-control" asp-for="PlaceofBirth">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">2</span>
                                        <span class="input-group-text text-muted">Дата рождения</span>
                                        <input type="date" class="form-control" placeholder="Дата рождения" asp-for="Birthday">
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ДП_WebУчетИностранныхСтудентов/Views/StudentCard/EditStudentCard.cshtml
@model EditStudentCardViewModel

@{
    ViewBag.Title = "Редактирование карточки";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h2>Редактирование карточки студента</h2>
    </div>
    <div class="row mx-auto d-flex justify-content-center align-items-center">
        <div class="col-12">
            <div class="border border-3 border-success rounded m-1 bg-list-block">
                <div class="border border-3 border-success rounded m-2 bg-white">
                    <form class="m-2" method="post" asp-controller="StudentCard">
                        <input type="hidden" asp-for="Surname">
                        <input type="hidden" asp-for="Name">
                        <input type="hidden" asp-for="Patronymic">
                        <input type="hidden" asp-for="Birthday">
                        <input type="hidden" asp-for="Faculty">
                        <input type="hidden" asp-for="Country">
                        <input type="hidden" asp-for="PlaceofBirth">
                        <input type="hidden" asp-for="Gender">
                        <div class="validation text-danger" asp-validation-summary="ModelOnly"></div>
                        <input type="hidden" asp-for="PersonalDetailsId" value="@Model.PersonalDetailsId" />
                        <div class="row mx-auto">
                            <div class="col-12 d-flex justify-content-center align-items-center">
                                <h3>Карточка студента</h3>
                            </div>
                            <div class="col-12 d-flex justify-content-center align-items-center mb-3">
                                Личные данные
                            </div>
                            <div class="col-12">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Фамилия, имя, отвество</span>
                                        <input type="text" class="form-control" asp-for="Surname">
                                        <input type="text" class="form-control" asp-for="Name">
                                        <input type="text" class="form-control" asp-for="Patronymic">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Факультет</span>
                                        <input type="text" class="form-control" asp-for="Faculty">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Гражданство</span>
                                        <input type="text" class="form-control" asp-for="Country">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Пол</span>
                                        <input type="text" class="form-control" asp-for="Gender">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Дата рождения</span>
                                        <input type="date" class="form-control" asp-for="Birthday">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">Место рождения</span>
                                        <input type="text" class="form-control" asp-for="PlaceofBirth">
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-12 col-md-6">
                                <fieldset disabled>
                                    <div class="input-group mb-3">
                                        <span class="input-group-text text-muted">2</span>
                                        <span class="input-group-text text-muted">Дата рождения</span>
                                        <input type="date" class="form-control" placeholder="Дата рождения" asp-for="Birthday">
                                        <div>
                                            <span class="form-text text-danger" asp-validation-for="Birthday"></span>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                            
                            <div class="col-12 d-flex justify-content-center align-items-center">
                                <h3>ПАСПОРТА</h3>
                            </div>
                            <div class="col-12">
                                <div class="mb-3 col-12 d-flex justify-content-center">
                                    <input type="submit" asp-action="AddPassportInfoToStudentCard" value="Добавить паспорт" class="btn btn-outline-success" />
                                </div>
                                <div class="row mx-auto d-flex align-items-center">
                                    @if (Model != null && Model.Passports != null && Model.Passports.Count > 0)
                                    {
                                        @for (var i = 0; i < Model.Passports.Count; i++)
                                        {
                                            <input type="hidden" asp-for="@Model.Passports[@i].Created" />
                                            <div class="col-12 col-md-4  d-flex justify-content-center justify-content-md-start align-items-center">
                                                <div class="border border-3 border-success rounded m-1 @(Model.Passports[@i].ValidUntil?.Date < DateTime.Now.Date ? "bg-danger" : "bg-list-block")">
                                                    <div class="border border-3 border-success rounded m-2 bg-white">
                                                        <div class="m-1">
                                                            <div class="input-group">
                                                                <span class="input-group-text text-muted">Номер</span>
                                                                <input type="text" class="form-control" asp-for="@Model.Passports[@i].Number" />
                                                            </div>
                                                            <hr>
                                                            <div class="input-group">
                                                                <span class="input-group-text text-muted">Дата выдачи</span>
                                                                <input type="date" class="form-control" asp-for="@Model.Passports[@i].DateOfIssue" />
                                                            </div>
                                                            <hr>
                                                            <div class="input-group">
                                                                <span class="input-group-text text-muted">Дата истечения</span>
                                                                <input type="date" class="form-control" asp-for="@Model.Passports[@i].ValidUntil" />
                                                            </div>
                                                            <div class="mt-3 d-flex justify-content-center">
                                                                <input type="submit" asp-action="RemovePassportInfoFromStudentCard" asp-route-index="@i" value="Удалить" class="btn btn-success" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                            <div class="col-12 d-flex justify-content-center align-items-center">
                                <h3>РЕГИСТРАЦИЯ</h3>
                            </div>
                            <div class="col-12">
                                <div class="mb-3 col-12 d-flex justify-content-center">
                                    <input type="submit" asp-action="AddRegisterToStudentCard" value="Добавить регистрацию" class="btn btn-outline-success" />
                                </div>
                                <div class="row mx-auto d-flex align-items-center">
                                    @if (Model != null && Model.Registers != null && Model.Registers.Count > 0)
                                    {
                                        @for (var i = 0; i < Model.Registers.Count; i++)
                                        {
                                            <input type="hidden" asp-for="@Model.Registers[@i].Created" />
                                            <div class="col-12 col-md-4  d-flex justify-content-center justify-content-md-start align-items-center">
                                                <div class="border border-3 border-success rounded m-1 @(Model.Registers[@i].ValidUntil?.Date < DateTime.Now.Date ? "bg-danger" : "bg-list-block")">
                                                    <div class="border border-3 border-success rounded m-2 bg-white">
                                                        <div class="m-1">
                                                            <div class="input-group">
                                                                <span class="input-group-text text-muted">Тип</span>
                                                                <input type="text" class="form-control" asp-for="@Model.Registers[@i].Info" />
                                                            </div>
                                                            <hr>
                                                            <div class="input-group">
                                                                <span class="input-group-text text-muted">Дата истечения</span>
                                                                <input type="date" class="form-control" asp-for="@Model.Registers[@i].ValidUntil" />
                                                            </div>
                                                            <div class="mt-3 d-flex justify-content-center">
                                                                <input type="submit" asp-action="RemoveRegisterFromStudentCard" asp-route-index="@i" value="Удалить" class="btn btn-success" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Обновить</button>
                        <button align="center" asp-action="GetFile" type="submit" class="btn btn-default">В файл</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ДП_WebУчетИностранныхСтудентов/Views/StudentCard/History.cshtml
@model IEnumerable<GetStudentCardViewModel>

@{
    ViewBag.Title = "История карточек";
    Layout = "_Layout";
}

<div class="container">
    <div class="d-flex justify-content-center justify-content-md-start">
        <h1>История карточки:</h1>
    </div>
    @foreach (var item in Model)
    {
        <div class="border border-3 border-success rounded-pill m-1 bg-list-block">
            <div class="border border-3 border-success rounded-pill m-2 bg-white">
                <div class="row mx-auto">
                    <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-start align-items-center fs-5">
                        Дата изменения: @item.Created
                    </div>
                    <div class="col-12 col-md-6 d-flex justify-content-center justify-content-md-end align-items-center">
                        <div class="m-1">
                            <a asp-controller="StudentCard" asp-action="EditStudentCard" asp-route-Id="@item.Id"><input type="button" class="btn btn-success" value="Редактировать"></a>
                        </div>
                        <div class="m-1">
                            <form asp-controller="StudentCard" asp-action="DeleteStudentCard" method="post" asp-route-id="@item.Id">
                                <input class="btn btn-success" type="submit" value="Удалить" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>